### ISSUE TITLE
加载todaybefore插件的时候，报 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by wuweijie007** [B1ue1nWh1te/SeaBot_QQ#3]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 2181, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 2172, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1484, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/46471/project/SeaBot_QQ\bot.py", line 15, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\46471\.virtualenvs\SeaBot_QQ\lib\site-packages\nonebot\plugin\__init__.py", line 1081, in load_from_toml
    return load_all_plugins(set(plugins), set(plugin_dirs))
  File "C:\Users\46471\.virtualenvs\SeaBot_QQ\lib\site-packages\nonebot\plugin\__init__.py", line 1023, in load_all_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\46471\.virtualenvs\SeaBot_QQ\lib\site-packages\nonebot\plugin\__init__.py", line 945, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\46471\.virtualenvs\SeaBot_QQ\lib\site-packages\nonebot\plugin\manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\46471\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\46471\.virtualenvs\SeaBot_QQ\lib\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\todaybefore\__init__.py", line 9, in <module>
    **groups = list(global_config.timing_group_id)
TypeError: 'NoneType' object is not iterable**

请问是python版本原因吗，我用的是3.7.9，nonebot2 == 2.0.0.a15

**Comment by wuweijie007** [comment]
正确的应该是：![image](https://user-images.githubusercontent.com/26738411/167336749-3e1d1c55-0218-49ee-a82c-d8afb8f59eac.png)
源码里是：TIMINIG_GROUP_ID=[""]
